export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";

export const DEFAULT_DEAL = {
  company: "",
  tagline: "",
  fallbackCompany: "Untitled Deal",
  stage: "Active diligence"
} as const;

export const UI_COPY = {
  appName: "DealProof",
  appDescription: "AI diligence red team for VC and PE claim verification.",
  emptyDeal: "No deal loaded",
  backendStatus: "Backend required",
  noAnalysis: "No analysis",
  welcomeTitle: "Add deal materials to begin.",
  welcomeBody: "Upload files or add a URL. DealProof will extract claims, check evidence, and draft a memo.",
  noMaterialsTitle: "No materials yet",
  noMaterialsBody: "Add files or a URL to start the diligence run.",
  questionPlaceholder: "Ask about the deal evidence...",
  settingsButton: "Deal settings",
  companyLabel: "Company",
  taglineLabel: "Tagline",
  createDealButton: "Create deal",
  seedDemoButton: "Load Harvey (legal AI)",
  seedDemo2Button: "Load SynthPay (fintech)",
  demoReadyTitle: "Materials loaded — ready to analyze.",
  demoReadyBody: "Demo materials are staged below. Hit \"Run analysis\" to start the full diligence pipeline.",
  runAnalysisButton: "Run analysis",
  uploadButton: "Upload",
  addUrlPlaceholder: "Add URL",
  addMaterialButton: "Add",
  runAgentButton: "Run agent",
  askButton: "Ask",
  answeringStatus: "Answering",
  answeringTitle: "Checking stored claims and evidence.",
  userLabel: "You",
  artifactsTitle: "Artifacts",
  claimLedgerTitle: "Claim ledger",
  claimLedgerPending: "Run the agent to extract verifiable claims.",
  riskMemoTitle: "Risk memo",
  riskMemoPending: "Run the agent to generate the memo.",
  icReadinessTitle: "IC readiness",
  icReadinessPending: "Run the agent to unlock IC readiness.",
  icReadinessPanelTitle: "IC readiness workbench",
  icReadinessScoreLabel: "Readiness",
  icBlockersLabel: "Blockers",
  topGatingIssueLabel: "Top gating issue",
  criticalBlockersTitle: "Critical blockers",
  evidenceRequestsTitle: "Evidence requests",
  resolvedItemsTitle: "Resolved items",
  noCriticalBlockers: "No critical blockers.",
  noEvidenceRequests: "No evidence requests.",
  noResolvedItems: "No resolved items yet.",
  claimsEyebrow: "Claim Ledger",
  evidenceEyebrow: "Evidence Drawer",
  memoEyebrow: "Memo",
  memoTitle: "Red team memo",
  executiveSummaryTitle: "Executive summary",
  thesisAssessmentTitle: "Thesis assessment",
  evidenceMapTitle: "Evidence map",
  decisionDriversTitle: "Decision drivers",
  exportMarkdownButton: "Export Markdown",
  keyStrengthsTitle: "What we can trust",
  materialRisksTitle: "What remains unproven",
  followUpQuestionsTitle: "What would change the decision",
  markdownPreviewTitle: "Markdown preview",
  answerTitle: "DealProof answer",
  streamingUnavailable: "Streaming is not available in this browser.",
  createdDealPrefix: "Created",
  seededDealPrefix: "Seeded",
  sourceMaterialsLoaded: "source materials loaded.",
  materialsQueued: "materials queued for analysis.",
  pending: "Pending",
  addedMaterialTitle: "Added diligence material",
  runAgentTitle: "Run the diligence agent",
  analysisCompleteTitle: "Analysis complete",
  preparingAnalysis: "Preparing analysis",
  workingStatus: "Working",
  stoppedStatus: "Stopped",
  finishedStatus: "Finished",
  inputLabel: "Input",
  outputLabel: "Output",
  waitingForResult: "Waiting for result",
  defaultToolInput: "state",
  needsAttention: "Needs attention",
  complete: "Complete",
  working: "Working",
  exceptionsNeedReview: "exceptions need review.",
  evidenceLabel: "evidence"
} as const;
